# Generated by Django 5.0.4 on 2024-09-16 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina_css', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticias',
            name='visible',
            field=models.BooleanField(default=True),
        ),
    ]
